### PR TITLE
Flake8

### PR DESCRIPTION
**Pull request by jacobgarder**
Made some more flake8 formatting and added docstrings to older project files and created setup.cfg with proposed settings, please feel free to change! 
Entire project should now pass flake8.

### CODE REVIEW

**Comment by jacobgarder** [comment]
What do you think?
BTW, Is the version 0.1.6.0 uploaded? I see only 0.1.5.9 in pypi..

**Comment by endor-force** [comment]
Looks good Jacob, I will merge at update to pypi tomorrow. Thanks for taking the time to do the clean up :)

**Comment by jacobgarder** [comment]
Thanks! No problem! :)

**Comment by endor-force** [comment]
@jacobgarder Merged and pypi packaged is updated. v 0.1.6.1 is now available.

**Pull request merged**
